# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/Girls-Coding-Day-Jekyll-blog-4"

# 网页的标题
title: "一只小猪咪"
username: sjr
# 网站副标题
description: "哇！！！大美女！！！"

aboutme: "大美女日常"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
